### PR TITLE
[RDY] Throw InvalidEdgeFormatExceptions. Fixes #32

### LINKED ISSUE #32: EdgeParser does not throw any exceptions
Even on an invalid file format.

### PR DESCRIPTION
**Pull request by Balletie**
Throws an InvalidEdgeFormatException on lines with more or less than two node identifiers.

Also fixes a bug where a line with only spaces looped infinitely.
Blank or empty lines are silently ignored.

Fixes #32

### CODE REVIEW

**Comment by Unia** [comment]
:+1: Waiting for second review.

File: src/main/java/nl/tudelft/dnainator/parser/buffered/DefaultEdgeParser.java [hunk 1]
```diff
@@ -86,22 +107,30 @@ private int eatSpaces(int next) throws IOException {
 	private String parseDest() throws IOException, InvalidEdgeFormatException {
 		StringBuilder dest = new StringBuilder(ID_LENGTH_GUESS);
 		int point = eatSpaces(br.read());
+		boolean destParsed = false;
 		char next;
 
-		while (point != -1) {
+		parseLoop: while (point != -1) {
```
Comment (gfokkema) [inline src/main/java/nl/tudelft/dnainator/parser/buffered/DefaultEdgeParser.java]: https://gist.github.com/gfokkema/3459d91a610253e3f4f9

(I hate labels, especially when they're not necessary :p.

File: src/main/java/nl/tudelft/dnainator/parser/buffered/DefaultEdgeParser.java [hunk 2]
```diff
@@ -86,22 +107,30 @@ private int eatSpaces(int next) throws IOException {
 	private String parseDest() throws IOException, InvalidEdgeFormatException {
 		StringBuilder dest = new StringBuilder(ID_LENGTH_GUESS);
 		int point = eatSpaces(br.read());
+		boolean destParsed = false;
```
Comment (gfokkema) [inline src/main/java/nl/tudelft/dnainator/parser/buffered/DefaultEdgeParser.java]: Not really fond of this solution, but should not be a reason to block merging imo.

File: src/main/java/nl/tudelft/dnainator/parser/buffered/DefaultEdgeParser.java (hunk 1 above)
Comment (Balletie) [inline src/main/java/nl/tudelft/dnainator/parser/buffered/DefaultEdgeParser.java]: Didn't think of that, thanks

**Comment by gfokkema** [comment]
Looking good.

**Comment by pvanagtmaal** [comment]
LGTM, merging.
