### PR TITLE
[RDY] Fix SplashScreen showing no feedback when an exception occurs

### LINKED ISSUE #82: Splash screen does not handle exceptions correctly
When an exception occurs during initialising the application, the splash screen remains open and no exception dialog is shown. For example, when having two instances at once, Neo4j complains but the splash screen doesn't.

### PR DESCRIPTION
**Pull request by pvanagtmaal**
Fixes #82 
screen shot 2015-05-23 at 21 22 21

### CODE REVIEW

File: src/main/java/nl/tudelft/dnainator/ui/splashscreen/SplashScreen.java [hunk 1]
```diff
@@ -38,8 +39,20 @@ public void start(Stage primaryStage) throws Exception {
...
+		Platform.exit();
+		return false;
+	}
+
+	@Override
 	public void handleApplicationNotification(PreloaderNotification info) {
-		stage.hide();
+		if (info instanceof ErrorNotification) {
+			handleErrorNotification((ErrorNotification) info);
+		} else {
```
Comment (ohuang12) [inline src/main/java/nl/tudelft/dnainator/ui/splashscreen/SplashScreen.java]: I would prefer to have the splashscreen immediately hide when the error occurs, so you are only left with the exception.

**Comment by Unia** [comment]
LGTM! Next review may merge once Travis is done

**Comment by ohuang12** [comment]
Looks good now to me!
